name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest-cov

    - name: Lint with pylint
      continue-on-error: true
      run: |
        pylint --rcfile=.pylintrc src tests > pylint-report.txt

    - name: Check format with black
      continue-on-error: true
      run: |
        black --check src tests --config pyproject.toml  

    - name: Run Security Scan (Bandit)
      run: bandit -r . -o bandit_report.txt || true

    - name: Run pytest with coverage
      continue-on-error: true
      run: |
        export PYTHONPATH=$PYTHONPATH:/home/runner/work/Ci-Pipeline-Python/Ci-Pipeline-Python/src
        pytest --cov=src --cov-report=xml || true
        
    - name: Upload CI reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: CI reports
        path: |
          pylint-report.txt
          bandit_report.txt
          pytest_report.xml
