name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache Python dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Check cache status
      run: |
        if [ -d ~/.cache/pip ]; then
          echo "✅ Cache directory exists. Pip cache may be reused."
        else
          echo "❌ Cache directory not found. Dependencies will be downloaded."
        fi

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Pylint
      run: |
        pylint --rcfile=.pylintrc src tests > pylint-report.txt

    - name: Pytest
      run: |
        export PYTHONPATH=$PYTHONPATH:/home/runner/work/Ci-Pipeline-Python/Ci-Pipeline-Python/src
        pytest --cov=src --cov-report=xml --cov-report=html

    - name: Upload CI reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: CI reports
        path: |
          pylint-report.txt
          htmlcov/index.html
